### ISSUE TITLE
The license expired pop up needs to scroll down and center to the page .

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#10]
The license expired pop up ( that come on course first launch after course expired) is not according to design doc .
![7](https://cloud.githubusercontent.com/assets/7794513/6061820/f9b0386e-ad70-11e4-9967-949af3ae19cd.png)

**Comment by vanrajsinh-parmar** [comment]
Code fixed. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
