### ISSUE TITLE
If a course is expired and the and user get the notification for that mile stone. In that notification, the line "Your licence for Q Skills: Reading and Writing Pilot (special edition) will expire soon. Your Licence is expired.." conatin two full stop in last

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#13]
If a course is expired and the and user get the notification for that mile stone in that notification, the line "Your licence for Q Skills: Reading and Writing Pilot (special edition) will expire soon. Your Licence is expired.." conatin two full stop in last
![untitled](https://cloud.githubusercontent.com/assets/7794513/6075183/a6b12686-adf3-11e4-9fe4-3cde6c7320ae.png)

**Comment by besiddharth** [comment]
Corrected. Please re-test.

**Comment by rahul-kumar11** [comment]
retested and passed
