### ISSUE TITLE
If the license of a course is expired and user launch the course the user get the license expired pop up and if user click on "use course as read only" then the user is redirected to my home page.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#14]
If the license of a course is expired and user launch the course the user get the license expired pop up and if user click on "use course as read only" then the user is redirected to my home page.

**Comment by vanrajsinh-parmar** [comment]
Code fixed. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
