### ISSUE TITLE
If user click on renew link then the "renew licence" pop up appear do not fill any data in access code text box and click on "continue" the user will get an error "Please enter an access code" now if user try to enter any character or numeric value  in text box the "continue" and "cancel" button will be out side from the text box.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#15]
if user click on renew link then the "renew licence" pop up appear do not fill any data in access code pop and click on "continue" the user will get an error "Please enter an access code" now if user try to enter any character or numeric value  in text box the "continue" and "cancel" button will be out side from the text box.
![9](https://cloud.githubusercontent.com/assets/7794513/6075346/5a81ac06-adf6-11e4-94ac-f8c549c2a60b.png)

**Comment by dharamveerSanodiya** [comment]
Bus resolved. Please check.

**Comment by rahul-kumar11** [comment]
retested and passed
