### ISSUE TITLE
 Some of the notification with title "Q Skills: Reading and Writing Pilot (special edition) licence is due to expire" has Indian time as expire but some have UK expire time. Please uniform time in all the notification.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#18]
Some of the notification with title "Q Skills: Reading and Writing Pilot (special edition) licence is due to expire" has Indian time as expire but some have UK expire time. Please uniform time in all the notification.

**Comment by besiddharth** [comment]
Removed the time conversion. It will take only the system time according to timezone set.

**Comment by rahul-kumar11** [comment]
retested and passed
