### ISSUE TITLE
The user get exception when user provide a delete class joing code on "enter joining code or use as self study" pop up. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#19]
Steps
1-Click on access content
2-Enter valid access code
3-Enter a class joining code that is deleted in "enter joining code " pop up.
![10](https://cloud.githubusercontent.com/assets/7794513/6076761/a24307da-ae0d-11e4-8b85-bdef9f7a17ad.png)

**Comment by NitinLeuva** [comment]
Rahul,

This is not related to Access content or any of the new changes, it is an existing issue. Also discussed with you before as well to check it on UAT if it seems to an exisitng issue.

This has issue with joining code work flow and should be corrected. Please assign it to Dharam. Also lower the priority.

Nitin

**Comment by rahul-kumar11** [comment]
Please do needful according to above comment

**Comment by rahul-kumar11** [comment]
retested and passed
