### ISSUE TITLE
If a user has the expired license for a course, then org admin add the user in a class which have the same course. Then the on the view visible screen the "activate content with" link will be there for the new class. But if the user click on view hidden page , Then for the new class the "use content with "link will be there. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#20]
If a user has the expired license for a course, then org admin add the user in a class which have the same course. Then the on the view visible screen the "activate content with" link will be there for the new class. But if the user click on view hidden page , Then for the new class the "use content with "link will be there.

**Comment by vanrajsinh-parmar** [comment]
Code changed, Issue resolved. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
