### ISSUE TITLE
If a user is in two class for a course user has activate the course in some class then for the second class he will get use content with.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#22]
If a user is in two class for a course user has activate the course in some class then for the second class he will get use content with.
1- User click on use content with then user will moved to that class with read only copy of first class.
2. Now the licence is expired of that course.
3. Org admin archived the expired course in new class.
4. On archive screen every thing is right. 
5. But on visible screen, course will be seen in the old class with renew link.

**Comment by rahul-kumar11** [comment]
marking is as existing because if we do in normal scenario then the course will be displayed in read only class on visible .

**Comment by vanrajsinh-parmar** [comment]
Code fixed. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
