### ISSUE TITLE
If a user is created in org and join a class of that org then he will get "Additional Info " Pop up. The user should not get that pop up.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#24]
If a user is created in org and join a class of that org then he will get "Additional Info " Pop up. The user should not get that pop up.

**Comment by NitinLeuva** [comment]
Rahul,

I need a detailed step on this, if user created in Org and then logged in then additional filed should be filled at partial registration.

Please provide detailed steps also it seems like an existing issue, if you have steps please reproduce it on UAT to check existence.

**Comment by rahul-kumar11** [comment]
--Steps To reproduce---
Create a student user in a org.
Login with student in the system
Click on join class.
In join class pop up put a valid joining code of a class og the org in which user is created. 
click on "Join"
access course pop up will appear
click on "ok"
"additional info " pop up will appear 
The pop up should not appear because the user join the class in which he is already present.

**Comment by rahul-kumar11** [comment]
This is not the existing issue i have checked on UAT.

**Comment by NitinLeuva** [comment]
Rahul,

Is this related to 53?

Does user get the org defined filed on Partial registration page?

Also when the user has joined the class first time as you mentioend in the last step above?

**Comment by NitinLeuva** [comment]
Can you check now?

**Comment by rahul-kumar11** [comment]
yes checked this is related to 53 so i am closing it marking it as duplicate of 53

Duplicate of 53
