### ISSUE TITLE
If the course is expired in a class then all the use content with link will become the "activate content with link" but the those activate link is not working properly. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#25]
If the course is expired in a class then all the use content with link will become the "activate content with link" but the those activate link is not working properly.

**Comment by rahul-kumar11** [comment]
retested and passed

**Comment by vanrajsinh-parmar** [comment]
Code fixed. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
