### ISSUE TITLE
if a user has a course that has one read only copy and one use content with class and in one class it is active. The use content with link and read only link is displayed in one line with some separation. But if the licence is expired of that course then then "use content with link" is converted in activate with link . and the link of read only is in different line with two or three line gap.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#26]
if a user has a course that has one read only copy and one use content with class and in one class it is active. The use content with link and read only link is displayed in one line with some separation. But if the licence is expired of that course then then "use content with link" is converted in activate with link . and the link of read only is in different line with two or three line gap.
![11](https://cloud.githubusercontent.com/assets/7794513/6092286/e539892e-aefd-11e4-93f1-81c3c81b82e5.png)

**Comment by vanrajsinh-parmar** [comment]
Code fixed. Issue resolved. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
