### ISSUE TITLE
If user is in two class and both the class have same course and user have activate the course in one class then for the second class there will be the use content with link . If the course licence is expired then the use content with link converted in "activate with class" and renew link  will be there. But the course title and image must be the link to launch the course in the expired class.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#27]
If user is in two class and both the class have same course and user have activate the course in one class then for the second class there will be the use content with link . If the course licence is expired then the use content with link converted in "activate with class" and renew link  will be there. But the course title and image must be the link to launch the course in the expired class.
![12](https://cloud.githubusercontent.com/assets/7794513/6092315/d94f9ff8-aefe-11e4-8d52-0a1da99bcc77.png)

**Comment by vanrajsinh-parmar** [comment]
Code fixed, issue resolved. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
