### ISSUE TITLE
A user has expired licence in a class and one activate with class link and one read only copy of the self study when the user try to renew the course, he gets the exception. The user get the exception when he click on continue after putting access code in access code text ox on renew pop up.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#28]
A user has expired licence in a class and one activate with class link and one read only copy of the self study when the user try to renew the course, he gets the exception. The user get the exception when he click on continue after putting access code in access code text ox on renew pop up.
![13](https://cloud.githubusercontent.com/assets/7794513/6092389/8bbd9818-af02-11e4-845c-b3d1d8d3f90e.png)

**Comment by vanrajsinh-parmar** [comment]
Hi Rahul,

I have tried to reproduce this issue. But I didn't get any exception. It is working fine and license get renewed without any problem.

Can you please retest and let me know if any issue?

**Comment by rahul-kumar11** [comment]
retested and passed
