### ISSUE TITLE
When user activate a course in self study and get the notification for " licence is due to expire " the display name replace sting is not working.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#3]
When user activate a course in self study and get the notification for " licence is due to expire " the display name replace sting is not working properly.
![1](https://cloud.githubusercontent.com/assets/7794513/6058599/d05868dc-ad4e-11e4-8a96-c0cd45ebdfb5.png)

**Comment by besiddharth** [comment]
Corrected. Please verify.

**Comment by rahul-kumar11** [comment]
Not working effectively and in some cases if user activate the course in class , teacher name is coming

**Comment by besiddharth** [comment]
This was due to DB script not ran. The script has been updated. Please verify.

**Comment by rahul-kumar11** [comment]
retested and passed
