### ISSUE TITLE
If user enter a access code for a course that is already in validate state. The user will get the pop of enter joining code but user should not get this pop up.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#30]
If user enter a access code for a course that is already in validate state. The user will get the pop of enter joining code but user should not get this pop up.

**Comment by NitinLeuva** [comment]
Rahul This is fixed, please check.

Assigning Vanraj to work on method UpdateAccessCode... in userdal

**Comment by NitinLeuva** [comment]
Rahul Please check and assign back to Vanraj as per above comment.

Nitin

**Comment by rahul-kumar11** [comment]
Vanraj please check.

**Comment by vanrajsinh-parmar** [comment]
Nitin,

I have removed addition check for consumed code from the method UpdateAccessCode as discussed with you.

Also removed additional overridden method introduced by you as it is no longer needed (after removing consumed check) as per our discussion.

Rahul,
Please retest this defect again. And inform Nitin, if there is any issue.

**Comment by rahul-kumar11** [comment]
retested and passed
