### ISSUE TITLE
There are multiple notification coming for the same class if the user licence is about to expiry and the validity hit the miles stone in which "notification to teacher" is true.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#31]
There are multiple notification coming for the same class if the user licence is about to expiry and the validity hit the miles stone in which "notification to teacher" is true.
![14](https://cloud.githubusercontent.com/assets/7794513/6096539/f3dc6a54-afbc-11e4-8062-8ac02646ceef.png)

**Comment by besiddharth** [comment]
Not able to reproduce. Please double check from your end.

**Comment by rahul-kumar11** [comment]
retested and passed
