### ISSUE TITLE
The cs admin is not able to renew the licence for any student.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#32]
The cs admin is not able to renew the licence for any student.

**Comment by NitinLeuva** [comment]
As per discussion with OUP at design time, this is not part of requirement. refer R16-Requirement-questionnaire in https://10.215.40.12/svn/Enrolment/trunk/EnrolmentDocuments/Release 16 SVN.

Please close this.

**Comment by rahul-kumar11** [comment]
According to the comment i am closing issue
