### ISSUE TITLE
If a student try to renew the licence of a expired  course using access content, he get the exception

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#33]
If a student try to renew the licence of a expired  course using access content, he get the exception
![15](https://cloud.githubusercontent.com/assets/7794513/6096577/8a607d16-afbe-11e4-8673-ca8eee649a76.png)
.

**Comment by NitinLeuva** [comment]
Siddharth/Vanraj,

![image](https://cloud.githubusercontent.com/assets/7794349/6126053/490059d4-b114-11e4-89b7-bee24bf150fd.png)

**Comment by NitinLeuva** [comment]
Still we are using Name ? from profile store. We already have similiar isue in rel 15.

**Comment by besiddharth** [comment]
Corrected. Please verify.

**Comment by rahul-kumar11** [comment]
retested and passed
