### ISSUE TITLE
If a user launch the course in a class now the teacher of that remove that user and user licence is not expired. The course should be moved to self study. But the course is not moved to self study but for that course get the read only copy of that class.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#34]
If a user launch the course in a class now the teacher of that remove that user and user licence is not expired. The course should be moved to self study. But the course is not moved to self study but for that course get the read only copy of that class.

**Comment by dharamveerSanodiya** [comment]
Bug resolved. Please check.

**Comment by rahul-kumar11** [comment]
retested and passed
