### ISSUE TITLE
If a user has launch a course in a class and his licence is expired user does not have any read only and any use content with link then user will get the read only copy of the class on view hidden screen. But user get the read only copy on visible with renew link.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#35]
If a user has launch a course in a class and his licence is expired user does not have any read only and any use content with link then user will get the read only copy of the class on view hidden screen. But user get the read only copy on visible with renew link.
![16png](https://cloud.githubusercontent.com/assets/7794513/6097129/e4f3c5a4-afd6-11e4-9393-36f358fe1b99.png)

**Comment by vanrajsinh-parmar** [comment]
Code fixed. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
