### ISSUE TITLE
If a user has launch a course in a class and his licence is expired user has any read only and but no use content with link then user will get the all read only copy of the class on view hidden screen. But user get activate with class link for both the class and on vie hidden every class has renew link with read only copy

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#36]
If a user has launch a course in a class and his licence is expired user has any read only and but no use content with link then user will get the all read only copy of the class on view hidden screen. But user get activate with class link for both the class and on vie hidden every class has renew link with read only copy
![17](https://cloud.githubusercontent.com/assets/7794513/6097158/3952b08c-afd8-11e4-8309-27d1cd31cfbd.png)
![18](https://cloud.githubusercontent.com/assets/7794513/6097160/3f4edd1c-afd8-11e4-9dd4-c7dd6eca0450.png)

**Comment by vanrajsinh-parmar** [comment]
Code fixed. Please retest.

**Comment by rahul-kumar11** [comment]
Check this scenario---
1-User in a class (ex class-1), and class has two courses (ex C1 and C2).
2-User has activate the course ex C1 and launched it.
3- Now user has join a class (ex-class-2) that contain course C1.
4-user will get the pop "do you want to change the class of these course" and user click on "use content with" button.
5. Now the course C1 will moved to class-2 with read only copy of class-1 and course C2 will be in class-1.
6- Now the licence of course C1 has expired.
7- Org admin remove the user from class-2.
8- Now  user will get two read only copy of the course C1 both should be displayed on "hidden" course list.
But the course c1 is displayed in class-1  , the link and image is disable of the course and the read only copy link is displayed.

**Comment by vanrajsinh-parmar** [comment]
Code fixed for above last comment by Rahul. Issue resolve. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
