### ISSUE TITLE
If a user in a class with self study instance read only and the licence is expired. Now of any teacher move that user to any class which contain the expired licence course , the course moves to self study. The course should be moved to the new class.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#37]
If a user in a class with self study instance read only and the licence is expired. Now of any teacher move that user to any class which contain the expired licence course , the course moves to self study. The course should be moved to the new class.

**Comment by dharamveerSanodiya** [comment]
Bug resolved. Please check.

**Comment by rahul-kumar11** [comment]
retested and passed
