### ISSUE TITLE
In token search if user does not put in access code in text box and click on "search" the system the message "the following error occurs" but no error message is displayed.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#38]
In token search if user does not put in access code in text box and click on "search" the system the message "the following error occurs" but no error message is displayed.

**Comment by NitinLeuva** [comment]
Siddharth,

This is an existing UI issue, could you check this.

Nitin

**Comment by rahul-kumar11** [comment]
retested and passed
