### ISSUE TITLE
If user click on access content ," enter access code " pop up will open, user put a valid access code and click on "OK", "enter joining code" pop up will appear user click on "use as self study" link. . The course will be joined in self study but access code will be in "validate state". User apply same process for another course. Now user has two different course in self study but in validate state. Now user login with EAC and mapped the one course access code to another course (User has already that course in validate state). Now if user launch that  course (ex c1) the other course (ex -c2) will be launched because access code mapped to c2 course. But when user exit the course and go to my home only c2 course will be displayed.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#39]
If user click on access content ," enter access code " pop up will open, user put a valid access code and click on "OK", "enter joining code" pop up will appear user click on "use as self study" link. . The course will be joined in self study but access code will be in "validate state". User apply same process for another course. Now user has two different course in self study but in validate state. Now user login with EAC and mapped the one course access code to another course (User has already that course in validate state). Now if user launch that  course (ex c1) the other course (ex -c2) will be launched because access code mapped to c2 course. But when user exit the course and go to my home only c2 course will be displayed.

**Comment by NitinLeuva** [comment]
If the code is redirected in EAC to new product and if the user already have this product in SS copy in his account then Enrolment should not create any new enrolment. But the existing product should be launched which was already in SS copy.

Nitin

**Comment by rahul-kumar11** [comment]
retested and passed
