### ISSUE TITLE
The semicolon needs to remove from popup.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#4]
when user gets a pop up on course launch to notify user about the remaining validity of the course. The pop up does not have any name. There should be some content on the pop up . There is a semi colon on the pop up which should not be there.
![2](https://cloud.githubusercontent.com/assets/7794513/6058854/6d4d9264-ad51-11e4-962c-947b02f1a687.png)

**Comment by vanrajsinh-parmar** [comment]
This should be suggestion, not enhancement.

**Comment by dharamveerSanodiya** [comment]
Rahul,
Bug is resolved. Please check and let me know if further modification is required.

**Comment by rahul-kumar11** [comment]
retested and passed
