### ISSUE TITLE
If the org admin try to create user and adding that user in class with valid access code  of a course present is in the class, org admin will get operation failed. and in status column the value will be failed.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#40]
If the org admin try to create user and adding that user in class with valid access code  of a course present is in the class, org admin will get operation failed. and in status column the value will be failed.

**Comment by dharamveerSanodiya** [comment]
Hi Rahul,
Bug is resolved. Please check.

**Comment by rahul-kumar11** [comment]
retested and passed
