### ISSUE TITLE
if an org admin try to update the student by adding that user in a class and provide valid access code of a course that is present in the class. Then the student is not updated and org admin will get exception.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#41]
if an org admin try to update the student by adding that user in a class and provide valid access code of a course that is present in the class. Then the student is not updated and org admin will get exception.

**Comment by dharamveerSanodiya** [comment]
Rahul,
Please check.

**Comment by rahul-kumar11** [comment]
retested and passed
