### ISSUE TITLE
CR-2704  If an org admin try to update some user using import user and the first record get the run time exception, then the other records must process. But the system will skip all the records having error "system errors occurs"

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#42]
CR-2704  If an org admin try to update some user using import user and the first record get the run time exception, then the other records must process. But the system will skip all the records having error "system errors occurs"

**Comment by besiddharth** [comment]
There was an issue with the logging. The changes what we implement for CR-2704 were working fine except the logging to DB part, which has been corrected now. Please re-test.

**Comment by rahul-kumar11** [comment]
retested and passed
