### ISSUE TITLE
If an org admin create a  user and left full name text box blank and fill all the valid data in other text box and click on create . The org admin  will get the error message "please enter a name" now click on full name text box and start writing . The error message removed but the the message "the following error occurred " is still there.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#43]
If an org admin create a  user and left full name text box blank and fill all the valid data in other text box and click on create . The org admin  will get the error message "please enter a name" now click on full name text box and start writing . The error message removed but the the message "the following error occurred " is still there.
![20](https://cloud.githubusercontent.com/assets/7794513/6124426/6eb2eeb6-b133-11e4-9ce4-df8d80621d21.png)

**Comment by rahul-kumar11** [comment]
Same case is happening for password and role field in all the browser.

**Comment by dharamveerSanodiya** [comment]
Rahul,
Bug resolved. Please check.

**Comment by rahul-kumar11** [comment]
retested and passed
