### ISSUE TITLE
If user  click on access content and  put an valid access code in access code text box and student join r that course in self study or in class . Now student launch that course and exit that course back to my home screen. Now user click on my home screen and if the remaining validity of the course hit any mile stone the user get the exception.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#46]
If user  click on access content and  put an valid access code in access code text box and student join r that course in self study or in class . Now student launch that course and exit that course back to my home screen. Now user click on my home screen and if the remaining validity of the course hit any mile stone the user get the exception.

**Comment by rahul-kumar11** [comment]
![22](https://cloud.githubusercontent.com/assets/7794513/6142403/e70dd2a6-b1db-11e4-9fdc-44bcb2b17fb4.png)

**Comment by besiddharth** [comment]
Resolved by code fix. Please re-test.

**Comment by rahul-kumar11** [comment]
retested and passed
