### ISSUE TITLE
If a user try to renew the course by clicking  renew link and put the access code of another course then the student gets exception 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#47]
If a user try to renew the course by clicking  renew link and put the access code of another course then the student gets exception 
![23](https://cloud.githubusercontent.com/assets/7794513/6142453/be81fbf4-b1dc-11e4-85e5-fd1631499e35.png)

**Comment by vanrajsinh-parmar** [comment]
Code fixed & issue resolved. Please retest

**Comment by rahul-kumar11** [comment]
retested and passed
