### ISSUE TITLE
if a course is activated in self-study  and the validity hit any miles stone then the course validity on my course list will be in red color. but if remaining validity is less than one min and user click on my home then the licence validity comes in normal  color. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#51]
if a course is activated in self-study  and the validity hit any miles stone then the course validity on my course list will be in red color. but if remaining validity is less than one min and user click on my home then the licence validity comes in normal  color.

**Comment by besiddharth** [comment]
Fixed. Please Validate.

**Comment by rahul-kumar11** [comment]
retested and passed
