### ISSUE TITLE
If user in  a class and class contain two or three courses, now user launch the course ex-C1 get the enter access code popup, user put the valid access code of c1 and click on "ok", the course will be launched in lms, now exits the course , the user will be moved to my home screen. wait till the licence of C1 will expiry. Now the licence of C1 has expired. Click on C2 (course 2 in same class), enter acess content pop up will appear. Put the access code of C1 in pop and click on " OK" , user get a pop up with a message "the course you have entered is not for the course. click on "ok" . User will moved to my home screen.  Now the course c1 will be displayed in same class but with read only copy and his licence is renewed.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#52]
If user in  a class and class contain two or three courses, now user launch the course ex-C1 get the enter access code popup, user put the valid access code of c1 and click on "ok", the course will be launched in lms, now exits the course , the user will be moved to my home screen. wait till the licence of C1 will expiry. Now the licence of C1 has expired. Click on C2 (course 2 in same class), enter acess content pop up will appear. Put the access code of C1 in pop and click on " OK" , user get a pop up with a message "the course you have entered is not for the course. click on "ok" . User will moved to my home screen.  Now the course c1 will be displayed in same class but with read only copy and his licence is renewed.

**Comment by rahul-kumar11** [comment]
![25](https://cloud.githubusercontent.com/assets/7794513/6147302/dfe2e9ea-b21b-11e4-864d-656f026fbc52.png)

**Comment by NitinLeuva** [comment]
Fixed please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
