### ISSUE TITLE
If an org admin create a student user and the org has some of the org defined field. Now when the student user login , then he will be moved to partial registration page and partial registration page must have the org defined field but they are not displayed until the  student click on "register".

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#53]
If an org admin create a student user and the org has some of the org defined field. Now when the student user login , then he will be moved to partial registration page and partial registration page must have the org defined field but they are not displayed until the  student click on "register".

**Comment by NitinLeuva** [comment]
Fixed please check.

**Comment by rahul-kumar11** [comment]
retested and passed
