### ISSUE TITLE
 if a student user click on access content and put valid access code with adding 7 to 8 space after it, and user click on "ok" the student will get "enter joining code" pop up  and if user click on "use course as self study" link then student gets exception. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#54]
If a student user click on access content and put valid access code with adding 7 to 8 space after it, and user click on "ok" the student will get "enter joining code" pop up  and if user click on "use course as self study" link then student gets exception. 
![26](https://cloud.githubusercontent.com/assets/7794513/6149099/56353700-b22c-11e4-86b3-ce707cbbe3f9.png)

**Comment by NitinLeuva** [comment]
Fixed please check.

nitin

**Comment by rahul-kumar11** [comment]
retested and passed
