### ISSUE TITLE
If a teacher is in two classes as teacher (lets take example class1 and class 2) and every class has course in it (C1 in class1 and C2 in class2) . Now there are two student  as S1 and S2. S1 is In class1 and S2 in class 2. Both the student has activate their courses. Now the S1 course remaining validity hits first mile stone and that mile stone has "notification to teacher" tag  true. Thus teacher gets the notification for that class class. Now the S2 course validity hits the miles stone. Now teacher must get the notification but the teacher is not getting the notification. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#55]
If a teacher is in two classes as teacher (lets take example class1 and class 2) and every class has course in it (C1 in class1 and C2 in class2) . Now there are two student  as S1 and S2. S1 is In class1 and S2 in class 2. Both the student has activate their courses. Now the S1 course remaining validity hits first mile stone and that mile stone has "notification to teacher" tag  true. Thus teacher gets the notification for that class class. Now the S2 course validity hits the miles stone. Now teacher must get the notification but the teacher is not getting the notification.

**Comment by besiddharth** [comment]
Not able to reproduce. Please double check from your end. Reducing the priority.

**Comment by rahul-kumar11** [comment]
retested and passed
