### ISSUE TITLE
A user has expired licence in a class and one activate with class link and one read only copy of the self study when the user try to renew the course by renew link then the course renew message comes but the course is not renewed. and if user try to launch the course then course is launched in grade book.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#56]
A user has expired licence in a class and one activate with class link and one read only copy of the self study when the user try to renew the course by renew link then the course renew message comes but the course is not renewed. and if user try to launch the course then course is launched in grade book.
![27](https://cloud.githubusercontent.com/assets/7794513/6149843/962d1e40-b231-11e4-9901-164c3e7d9234.png)

**Comment by vanrajsinh-parmar** [comment]
Code fixed. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
