### ISSUE TITLE
If a user try to renew the course by clicking renew link and put the access code of another course then the student get the error "The code you have entered is not for this course. Please ask your teacher for help." . When this error occurs the "cancel" and "continue" button will be out side the pop up. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#57]
If a user try to renew the course by clicking renew link and put the access code of another course then the student get the error "The code you have entered is not for this course. Please ask your teacher for help." . When this error occurs the "cancel" and "continue" button will be out side the pop up. 
![28](https://cloud.githubusercontent.com/assets/7794513/6162332/187a3304-b2a7-11e4-9676-1e342cfab259.png)

**Comment by vanrajsinh-parmar** [comment]
Code fixed. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
