### ISSUE TITLE
The constant is hard coded in constant.cs file, now in db it might be different as well for me it is 29 in DB and in constant it is to 24. Which seems to be a big problem when we will deploy this in live/UAT.  Release 15 made the template creation and editing from Org admin login. Please discuss this. Also prod and UAT has around 50 notification templates in db. So when we will insert this script the template id will be different. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#58]
The constant is hard coded in constant.cs file, now in db it might be different as well for me it is 29 in DB and in constant it is to 24. Which seems to be a big problem when we will deploy this in live/UAT.  Release 15 made the template creation and editing from Org admin login. Please discuss this.
Also prod and UAT has around 50 notification templates in db. So when we will insert this script the template id will be different.

**Comment by besiddharth** [comment]
Changed the code. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
