### ISSUE TITLE
If a student has more than one association for a product(like self study and class, class and class any combination) and student has launched the course. Now when the remaining validity of the course hit any milestone then course licence status on my course list must be red. Student must get the notification for the remaining validity. But neither the course status become red nor user gets the notification. 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#59]
If a student has more than one association for a product(like self study and class, class and class any combination) and student has launched the course. Now when the remaining validity of the course hit any milestone then course licence status on my course list must be red. Student must get the notification for the remaining validity. But neither the course status become red nor user gets the notification.

**Comment by besiddharth** [comment]
Fixed. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
