### ISSUE TITLE
Course is not displayed on my course screen.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#60]
Check this scenario---
1-User in a class (ex class-1), and class has a course (ex C1).
2-User has activate the course ex C1 and launched it.
3- Now user has join a class (ex-class-2) that contain course C1.
4-user will get the pop "do you want to change the class of these course" and user click on "use content with" button.
5. Now the course C1 will moved to class-2 with read only copy of class-1
6- Now the licence of course C1 has expired.
7- Org admin remove the user from class-2.
8- Now user will get two read only copy of the course C1 both should be displayed on "hidden" course list.
9- Now user join a class that contain course C1  and a course C2 . The course C2 displayed accordingly but the course C1 is not displayed on view visible screen.

**Comment by vanrajsinh-parmar** [comment]
--------- Mail snippet ------------

Hello All,

We have discussed new scenario like below and come to the below conclusion :

Scenario :
1) User have activated course c1 in class class1
2) license for course c1 is expired
3) Org admin remove user from class class1
4) course c1 become readonly and now display on hidden view
5) User join new class : class2 which have the same course c1

How to display course c1 with both class: class1 & class2 On visible view

Conclusion:
On visible view, course c1 is going to be display under any of the class with two link under course title
1) Class1 [Readonly] 2) Activate with class : class2

**Comment by vanrajsinh-parmar** [comment]
Code fixed. Issue Resolved. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
