### ISSUE TITLE
If user (should be the part of any org.)  has activated a course in class ( or self study). Now the licence of the course has expired. And the org admin  ( of the org in which user exits) add that user in a class that contain a course for which the user licence has expired. Now the student user login in the system. The course is displayed in class (or self study) with renew link. But for the class in which org admin added  that user get the "use content with link" . For this class user should get the "activate content with" link. This will happen when org admin add the user in class using "add user " , "add user to class" and import user functionality.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#61]
If user (should be the part of any org.)  has activated a course in class ( or self study). Now the licence of the course has expired. And the org admin  ( of the org in which user exits) add that user in a class that contain a course for which the user licence has expired. Now the student user login in the system. The course is displayed in class (or self study) with renew link. But for the class in which org admin added  that user get the "use content with link" . For this class user should get the "activate content with" link. This will happen when org admin add the user in class using "add user " , "add user to class" and import user functionality.

**Comment by vanrajsinh-parmar** [comment]
Code fixed. Please retest.

**Comment by rahul-kumar11** [comment]
retested and passed
