### ISSUE TITLE
if user licence for a course is about to expire and  ex 10 sec left and user click on my home . The user get exception.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/EnrolmentRel16#8]
if user licence for a course is about to expire and  ex 10 sec left and user click on my home . The user get exception.

![6](https://cloud.githubusercontent.com/assets/7794513/6060946/058eb9b0-ad69-11e4-95cc-2f8ce8831fae.png)

**Comment by besiddharth** [comment]
Couldn't reproduce but have changed to code to make sure about the mentioned error. Please check. Hence, decreasing the severity as well.

**Comment by rahul-kumar11** [comment]
retested and passed
